name: Swift

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        swift: [5.7.3, 5.8.1]
        os: [ubuntu-20.04, macos-latest]
        target: [Library, Server]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build (Debug)
      run: cd ${{ matrix.target }} && swift build -c debug
    - name: Build (Release)
      run: cd ${{ matrix.target }} && swift build -c release

  test:
    name: Test
    strategy:
      matrix:
        swift: [5.8.1]
        os: [ubuntu-20.04]
        target: [Library, Server]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.3.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Test (Debug)
      run: cd ${{ matrix.target }} && swift test --configuration debug
