name: Swift

on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        swift: [5.7.3, 5.8.1]
        os: [ubuntu-22.04, macos-latest]
        target: [Library, Server]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Build
      run: cd ${{ matrix.target }} && swift build -c debug
  
  test:
    name: Test
    strategy:
      matrix:
        swift: [5.8.1]
        os: [ubuntu-22.04]
        target: [Library, Server]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.4.0
      with:
        version: ${{ matrix.swift }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Test
      run: cd ${{ matrix.target }} && swift test -c debug

  release:
        name: Release Build
        runs-on: ubuntu-22.04
        steps:
        - name: Install Swift
          uses: slashmo/install-swift@v0.4.0
          with:
            version: 5.8.1
        - name: Checkout
          uses: actions/checkout@v2
        - name: Swift Version
          run: swift --version
        - name: Build
          run: cd Server && swift build -c release
        - uses: actions/upload-artifact@v3
          with:
            name: CampingServer
            path: Server/.build/x86_64-unknown-linux-gnu/release/CampingServer
